### ISSUE TITLE
Android SDK crashes when calling app with custom URL

### ISSUE THREAD

**Issue by langerhans** [Adobe-Marketing-Cloud/mobile-services#161]
Hello,

I'm experiencing a crash in the Android SDK (v 4.11), when starting an activity by custom URL.
The URL itself is valid as the intent fires normally, I even see the right activity with the correct data in the background while the app crashes in the analytics thread...

I'm pretty sure this might be happening cause the query string is using `&` also to denote the first parameter after the `?`. But since this is still considered valid by the system, it seems to be a bug in your implementation.

Following stack trace is what I get:

```
java.lang.StringIndexOutOfBoundsException: length=80; regionStart=1; regionLength=-1
   at java.lang.String.substring(String.java:1920)
   at com.adobe.mobile.Lifecycle.getAdobeDeepLinkQueryParameters(Lifecycle.java:709)
   at com.adobe.mobile.Lifecycle.checkForAdobeClickThrough(Lifecycle.java:642)
   at com.adobe.mobile.Lifecycle.start(Lifecycle.java:181)
   at com.adobe.mobile.Config$10.run(Config.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
   at java.lang.Thread.run(Thread.java:761)
```

**Comment by sbenedicadb** [comment]
Hey @langerhans,

We have opened an issue internally and will be fixing this in a future release.  

Thanks.

-steveb

**Comment by sbenedicadb** [comment]
Hey @langerhans,

Android SDK version 4.11.1 contains a fix for this issue, and has been released:

https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.11.1-Android

**Comment by langerhans** [comment]
Thank you @sbenedicadb, I can confirm the issue is fixed for us with the latest release!
