### ISSUE TITLE
[Android]Bad crash in Lifecycle

### ISSUE THREAD

**Issue by talentprince** [Adobe-Marketing-Cloud/mobile-services#275]
The crash seems increasing, the crash log is below.

Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=94; regionStart=95; regionLength=-1
       at java.lang.String.substring(String.java:1931)
       at com.adobe.mobile.Lifecycle.a(SourceFile:709)
       at com.adobe.mobile.Lifecycle.a(SourceFile:642)
       at com.adobe.mobile.Lifecycle.a(SourceFile:181)
       at com.adobe.mobile.Config$11.run(SourceFile:250)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

Any idea or thought to help me, thanks.

**Comment by talentprince** [comment]
found it's fix in 4.11.1 thanks
