### ISSUE TITLE
[Android] Adobe analytics crashing with Null pointer exception [ Android 9]

### ISSUE THREAD

**Issue by mohsin-sayyed** [Adobe-Marketing-Cloud/mobile-services#381]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.adobe.marketing.mobile.AnalyticsState.q()' on a null object reference
       at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(AnalyticsHitsDatabase.java:73)
       at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(AnalyticsHitsDatabase.java:104)
       at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(AnalyticsHitsDatabase.java:2)
       at com.adobe.marketing.mobile.HitQueue$1.run(HitQueue.java:53)
       at java.lang.Thread.run(Thread.java:764)

**Comment by shalehaha** [comment]
@mohsin-sayyed 
Which version of the Analytics extension are you on?

**Comment by mohsin-sayyed** [comment]
com.adobe.marketing.mobile:analytics:1.2.2

**Comment by shtomar-adb** [comment]
Hi @mohsin-sayyed 
Could you use the latest version of analytics sdk **1.2.6**.
If it doesn't fix the crash, could you share the logs without obfuscation

**Comment by stcheng-adobe** [comment]
Hi @mohsin-sayyed,

Did you get a chance to use the latest version?  Any updates?

**Comment by stcheng-adobe** [comment]
Hi @mohsin-sayyed,

A friendly reminder, are you able to follow up the issue with our recommendations?

**Comment by rymorale** [comment]
Closing this issue as it has not had any activity in some time. Please re-open it if the issue is still occurring.
